###
#
##

.PHONY: *

build:
	./gradlew build
# build

bootRun:
	./gradlew bootRun
# bootRun

request_auth:
	curl -i localhost:8080/mappings -u user:password
# request_auth

request_noauth:
	curl -i localhost:8080/mappings
# request_noauth

# Makefile
