###
#
##

build:
	./gradlew build
# build

bootRun:
	./gradlew bootRun
# bootRun

request:
	curl -s localhost:8080 -u admin:password
	@echo -----
	curl -s localhost:8080 -u billy:bob
# request

# Makefile
